def ekarepla():
	momotalk3("Hei, olen Mo Mo, mulla tulevaisuudesta tulee mieleen, laite jolla ymmärrän ihmisiä paremmin")

def tokarepla():
	momotalk3("Koska olen sosiaalinen ropotti, ja edustan tulevaisuuden teknolokiaa, kerron teille lyhyesti kone älystä")
	momotalk3("usein ihmiset viittaavat kone älyyn alkoritmeina, ja sanasta onkin muodostunut lähes synonyymi kone älylle, mutta kaikki alkoritmit eivät ole älykkäitä, yleisesti ottaen alkoritmi on vain perättäisiä ohjeita")
	momotalk3("kokeillaan käden heiluttamista alkoritmina")
	momotalk3("yksi, nosta kätesi")
	momotalk3("kaksi, siirä kättä vasemmalle")
	momotalk3("kolme, siirä kättä oikealle")
	momotalk3("neljä, toista kohdasta kaksi omaan tahtiin, eli siirä kättä vasemmalle, ja sitten vuorostaan oikealle")
	momotalk3("ollakseen älykäs, alkoritmin pitää olla muutakin kuin samanlaisena toistuvat ohjeet, alkoritmin tulee tulkita ympäristöään eli ddataa, ja valita toimintansa sen perusteella")
	momotalk3("Kkokeillaan sama kkäden lliikutus, siten että samalla havainnoit mitä ympärilläsi tapahtuu, ja annat sen vaikuttaa kkäden liikkeeseen")
	momotalk3("koneälyä voi llähestyä kkahdella tapaa")
	momotalk3("joko asettamalla sääntöjä, joiden mukaan tulkinta ttehdään, tai opettamalla alkoritmi aiemmin mitatun datan perusteella")
	momotalk3("jälkimmäistä tapaa kutsutaan koneoppimiseksi")

def kolmasrepla():
	momotalk3("On parempi tehdä harjoitus silmät kiinni, koska näköaisti on määräävä aistimme, Näin pystyt keskittymään muihin aisteihin ja kehon mikroliikkeisiin")
	momotalk3("Voit ensin kuunnella miten hengität tänään, Hengitystä ei tarvitse muut taa, keskity vain aistimaan sisäänhengitys, ja uloshengitys")
	sleep(5)
	momotalk3("ovatko ne samanpituisia, onko niiden välissä taukoa?")
	sleep(5)
	momotalk3("mihin kehonosaan hengität?")
	sleep(5)
	momotalk3("voitko tuntea kehosi painon lattiaa vasten?, Antaa sen tippua lattian läpi, alakertaan, kellariin")
	sleep(5)
	momotalk3("Seuraavaksi voit hieman sskannata kkehoa läpi, mitkä kehonosat koskettavat lattiaa, mitkä kehonosat ovat hieman irti lattiasta.")
	sleep(5)
	momotalk3("Voit myös havainnoida miten vaatteet koskettavat ihoa")
	sleep(5)
	momotalk3("Esitän nyt filosofisen kysymyksen, kosketatko sinä lattiaa, vai koskettaako lattia sinua")
	momotalk3("Havainnoi tätä kysymystä kehossasi, ilman, että alat liikkumaan")
	sleep(5)
	momotalk3("nyt voit kokeilla tehdä pieniä mikro liikkeitä, painaa ehkä, jotain kehonosaa maahan")
	momotalk3("saatat tuntea, että jokin toinen kehonosa nousee näin ollen irti lattiasta")
	momotalk3("koskettatko sinä lattiaa, vai koskettaako lattia, sinua")
	sleep(5)
	momotalk3("voit lopettaa liikkumisen, ja jäädä paikoillesi, kuuntele nyt hengitystäsi, onko se muuttunut, aikaisemmasta?")
	sleep(3)
	momotalk3("seuraavaksi rullaa päätäsi omassa tahdissa,, hitaasti, maata pitkin oikealle, ja sitten hitaasti vasemmalle")
	momotalk3("älä mene ääriasentoon asti, pysy, mukavuusalueella")
	sleep(3)
	momotalk3("Anna nyt silmien johtaa liikettä, pää seuraa mukana, älä avaa silmiäsi, katso, oikealle, silmät kiinni, ja anna, pään seurata mukana")
	sleep(3)
	momotalk3("toista ssama vasemmalle")
	sleep(5)
	momotalk3("nyt voit avata silmät, ja toistaa saman, silmät auki, katso, oikealle, ja anna pään seurata, silmien liikettä, toista sama vasemmalle")
	sleep(7)
	momotalk3("hyvä, voit vähän, liikutella sormia, ja varpaita")
	sleep(5)
	momotalk3("kääntyä oikealle kyljelle, ja tulla sitä kautta istumaan")

def neljasrepla():
	momotalk3("seuraavaksi teemme harjoituksen, jossa keskitymme, eri kehonosien suhteeseen, valitsemme aina kaksi kehonosaa, jotka voimme viedä joko, lähelle toisiaan, tai kauas toisistaan, Koita tehdä viennit, mahdollisimman tarkasti alussa")
	momotalk3("Voitko Iina, näyttää miten harjoitus tehdään")
	sleep(2)
	momotalk3("oikea etusormi, ja vasen pikkuvarvas")
	sleep(3)
	momotalk3("vasen korva, ja vasen polvilumpio")
	sleep(3)
	momotalk3("häntäluu, ja pää")
	sleep(3)
	momotalk3("onko harjoitus selvä, sitten aloitetaan")

def viidesrepla():
	momotalk3("oikea peukalo, ja oikea kantapää")
	sleep(7)
	momotalk3("vasen olkapää, ja napa")
	sleep(7)
	momotalk3("oikea polvilumpio, ja vasen etuvarvas")
	sleep(7)
	momotalk3("nenä, ja rintakehä")
	sleep(7)
	momotalk3("vasen pohje, ja oikea kyynärpää")
	sleep(7)
	momotalk3("takaraivo, ja peppu")
	sleep(7)
	momotalk3("nyt voit valita kehonosat itse, voit siis viedä kaksi kehonosaa, joko lähelle, tai kauas toisistaan")
	momotalk3("voit säädellä tempoa, tee välillä nopeita, välillä hitaita vientejä, voit välillä antaa aivojen etulohkon, levätä, ja tehdä viennit, intuitiivisemmin")

def vikarepla():
	momotalk3("Timo Honkela on kirjoittanut kirjassa tekoälytutkijan testamentti, että kartta on oiva apuväline merkitysneuvottelussa, merkityksiä voidaan tarkastella moniulotteisina ilmiöinä")
	momotalk3("karttaa voi ajatella vertauskuvana, jonne merkitykset sijoittuvat, perinteisessä tekoäly tutkimuksessa, erityisesti kahdeksankymmentä luvulla, merkityksiä kuvattiin prototyyppeinä")
	momotalk3("prototyypeistä rakennettiin käsite verkkoja, jotka toimivat samalla käsitteiden määrittelyn välineinä, jolloin, näiden käsite verkkojen kraafinen esitysmuoto muistuttaa hämähäkinverkkoa tai pitsityötä")
	momotalk3("tällaisessa verkkomaisessa esitysmuodossa, kaikki solmukohdat kuvaavat jotakin käsitettä, äskeisessä tehtävässä, olleet paikat voi myös ajatella tällaisina solmukohtina")
